# <font color = aquamarine> Pandas
<font color = azure>

<div style = "text-align : left"> Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.
</div> 

<font color = aquamarine>

**Documentation**: 
 - **Pandas**: https://pandas.pydata.org/docs/
 - **Python**: https://docs.python.org/3/library/index.html

### <font color = Azure> Importing Pandas

In [1]:
import pandas as pd

### <font color = Azure> Working with tuples

##### <font color = antiquewhite> Building Tuples

In [2]:
# Empty Tuple
_tuple = ()
print(_tuple)

# Values to Tuple
_tuple = 1,2,3
print(_tuple)

# From variables
name = 'Civic'
value = 85000
_tuple = (name,value)
print(_tuple)

# From lists
_tuple = tuple(['Civic','Golf','Jetta','i30'])
print(_tuple)

()
(1, 2, 3)
('Civic', 85000)
('Civic', 'Golf', 'Jetta', 'i30')

##### <font color = antiquewhite> Selection

In [3]:
print('First element: ',_tuple[0])
print('Last element: ',_tuple[-1])
print('First to second element: ',_tuple[0:2])
print('Position of Civic', _tuple.index('Civic'))

First element:  Civic
Last element:  i30
First to second element:  ('Civic', 'Golf')
Position of Civic 0

##### <font color = antiquewhite> Iterations

In [4]:
for _ in _tuple: print(_, end = ' | ')

Civic | Golf | Jetta | i30 |

In [5]:
# zip()
names =  ['Civic','Golf','Jetta','i30']
values = [85000,90000,120000,130000]
print(list(zip(names,values)))

[('Civic', 85000), ('Golf', 90000), ('Jetta', 120000), ('i30', 130000)]

In [6]:
for _ in zip(names,values):
    print(_)

('Civic', 85000)
('Golf', 90000)
('Jetta', 120000)
('i30', 130000)

In [7]:
for name, value in zip(names,values):
    if value < 100000:
        print(name,value)

Civic 85000
Golf 90000

##### <font color = antiquewhite> Unpacking Tuples

In [8]:
name1,name2,name3,name4 = _tuple
print(name1,name2,name3,name4)

A , _ , _, B = _tuple
print(A,B)

_ , C , *_ = _tuple
print(C)

Civic Golf Jetta i30
Civic i30
Golf

### <font color = Azure> Dictionaries

##### <font color = antiquewhite> Building Dictionaries

In [9]:
names = ['John','Alice','Bob']
phones = ['(415) 555-2671', '(415) 555-2357', '(415) 555-2963']

agenda = {'John': '(415) 555-2671', 'Alice': '(415) 555-2357', 'Bob': '(415) 555-2963'}
print(agenda)

agenda = dict(zip(names,phones))
print(agenda)

{'John': '(415) 555-2671', 'Alice': '(415) 555-2357', 'Bob': '(415) 555-2963'}
{'John': '(415) 555-2671', 'Alice': '(415) 555-2357', 'Bob': '(415) 555-2963'}

##### <font color = antiquewhite> Operations on dictionaries

In [10]:
print(agenda['John'])
print('Alice' in agenda)
print('Size: ', len(agenda))

(415) 555-2671
True
Size:  3

In [11]:
#Add a new element
agenda['Carlos'] = '(415) 555-2844'
agenda

{'John': '(415) 555-2671',
 'Alice': '(415) 555-2357',
 'Bob': '(415) 555-2963',
 'Carlos': '(415) 555-2844'}

In [12]:
# Delete an element
del agenda['John']
agenda

{'Alice': '(415) 555-2357',
 'Bob': '(415) 555-2963',
 'Carlos': '(415) 555-2844'}

##### <font color = antiquewhite> Methods

In [13]:
#Update -- Add or modify an element
agenda.update({'Carlos': '(415) 555-2846', 'Alisson' : '(415) 555-3345'})
agenda

{'Alice': '(415) 555-2357',
 'Bob': '(415) 555-2963',
 'Carlos': '(415) 555-2846',
 'Alisson': '(415) 555-3345'}

In [14]:
#Copy - Copy the dictionary
agenda_copy = agenda.copy()
del agenda_copy['Carlos'] # or agenda_copy.pop('Carlos')
print(agenda)
print(agenda_copy)
agenda_copy.pop('Carlos', 'Not found')

{'Alice': '(415) 555-2357', 'Bob': '(415) 555-2963', 'Carlos': '(415) 555-2846', 'Alisson': '(415) 555-3345'}
{'Alice': '(415) 555-2357', 'Bob': '(415) 555-2963', 'Alisson': '(415) 555-3345'}

'Not found'

In [15]:
#Clear - Remove all elements
agenda_copy.clear()
print(agenda_copy)

{}

##### <font color = antiquewhite> Iterations

In [16]:
agenda.keys()

dict_keys(['Alice', 'Bob', 'Carlos', 'Alisson'])

In [17]:
for _ in agenda.keys():
    print(agenda[_])

(415) 555-2357
(415) 555-2963
(415) 555-2846
(415) 555-3345

In [18]:
agenda.values()

dict_values(['(415) 555-2357', '(415) 555-2963', '(415) 555-2846', '(415) 555-3345'])

In [19]:
agenda.items()

dict_items([('Alice', '(415) 555-2357'), ('Bob', '(415) 555-2963'), ('Carlos', '(415) 555-2846'), ('Alisson', '(415) 555-3345')])

In [20]:
for _ in agenda.items():
    print(_)

('Alice', '(415) 555-2357')
('Bob', '(415) 555-2963')
('Carlos', '(415) 555-2846')
('Alisson', '(415) 555-3345')

In [21]:
for key, value in agenda.items():
    print(key, value)

Alice (415) 555-2357
Bob (415) 555-2963
Carlos (415) 555-2846
Alisson (415) 555-3345

### <font color = Azure> Series

In [22]:
names = ['John','Alice','Bob']
pd.Series(names)

0     John
1    Alice
2      Bob
dtype: object

### <font color = Azure> DataFrame

##### <font color = antiquewhite> Building DataFrames

In [27]:
# Create a DataFrame from a dictionary
dados = {
    'Name': ['Jetta Variant', 'Passat', 'Crossfox'], 
    'year': [2003, 1991, 1990],
    'km': [44410.0, 5712.0, 37123.0],
    '0_km': [False, False, False],
    'Value': [88078.64, 106161.94, 72832.16]
}

pd.DataFrame(dados)

            Name  year       km   0_km      Value
0  Jetta Variant  2003  44410.0  False   88078.64
1         Passat  1991   5712.0  False  106161.94
2       Crossfox  1990  37123.0  False   72832.16

In [37]:
# Reading an external file
df = pd.read_csv('db.csv',sep=';', index_col=0)
df

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

##### <font color = antiquewhite> Selection

In [41]:
# Selecting columns
print(type(df[['Ano']]))
df[['Ano']]

<class 'pandas.core.frame.DataFrame'>

                        Ano
Nome
Jetta Variant          2003
Passat                 1991
Crossfox               1990
DS5                    2019
Aston Martin DB4       2006
...                     ...
Phantom 2013           2014
Cadillac Ciel concept  1991
Classe GLK             2002
Aston Martin DB5       1996
Macan                  1992

[258 rows x 1 columns]

In [42]:
print(type(df['Ano']))
df['Ano']

<class 'pandas.core.series.Series'>

Nome
Jetta Variant            2003
Passat                   1991
Crossfox                 1990
DS5                      2019
Aston Martin DB4         2006
                         ...
Phantom 2013             2014
Cadillac Ciel concept    1991
Classe GLK               2002
Aston Martin DB5         1996
Macan                    1992
Name: Ano, Length: 258, dtype: int64

In [43]:
# Selecting rows
df[0:3]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16

In [48]:
# .loc - Selecting rows and columns
df.loc[['Jetta Variant','Passat']]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94

In [49]:
df.loc[['Jetta Variant','Passat'],['Ano','Valor']]

                Ano      Valor
Nome
Jetta Variant  2003   88078.64
Passat         1991  106161.94

In [52]:
# .iloc - Selecting rows and columns by index
df.iloc[[1]]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94

In [55]:
df.iloc[[1,3,5],[1,2]]

                Ano  Quilometragem
Nome
Passat         1991         5712.0
DS5            2019            NaN
Palio Weekend  2012        10728.0

In [56]:
df.iloc[0:3,1:3]

                Ano  Quilometragem
Nome
Jetta Variant  2003        44410.0
Passat         1991         5712.0
Crossfox       1990        37123.0

##### <font color = antiquewhite> Query

In [57]:
df.head()

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10

In [58]:
df.Motor

Nome
Jetta Variant                  Motor 4.0 Turbo
Passat                            Motor Diesel
Crossfox                       Motor Diesel V8
DS5                            Motor 2.4 Turbo
Aston Martin DB4               Motor 2.4 Turbo
                                 ...
Phantom 2013                          Motor V8
Cadillac Ciel concept                 Motor V8
Classe GLK               Motor 5.0 V8 Bi-Turbo
Aston Martin DB5                  Motor Diesel
Macan                          Motor Diesel V6
Name: Motor, Length: 258, dtype: object

In [60]:
select = df.Motor == 'Motor Diesel'

In [65]:
df[select]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Effa Hafei Picape Baú,Motor Diesel,1991,102959.0,False,"['Controle de estabilidade', 'Painel digital',...",125684.65
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
New Fiesta Hatch,Motor Diesel,2017,118895.0,False,"['Sensor de estacionamento', 'Travas elétricas...",66007.16
Kangoo Express,Motor Diesel,2007,29132.0,False,"['Bancos de couro', 'Câmbio automático', 'Pilo...",146716.91
Fit,Motor Diesel,2013,44329.0,False,"['Freios ABS', 'Câmera de estacionamento', 'Câ...",77836.23
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Symbol,Motor Diesel,2016,117714.0,False,"['4 X 4', 'Piloto automático', 'Sensor crepusc...",133030.60
A4 Sedan,Motor Diesel,2002,30511.0,False,"['Câmera de estacionamento', '4 X 4', 'Travas ...",96369.04
A4 Avant,Motor Diesel,2014,17357.0,False,"['Teto panorâmico', '4 X 4', 'Bancos de couro'...",138946.88
Silver Shadow,Motor Diesel,2015,99052.0,False,"['4 X 4', 'Central multimídia', 'Ar condiciona...",143568.22
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Clio,Motor Diesel,1990,66437.0,False,"['4 X 4', 'Câmbio automático', 'Freios ABS', '...",111130.33
Série 3 M3 Coupé,Motor Diesel,2013,19896.0,False,"['Bancos de couro', 'Sensor de chuva', 'Ar con...",69219.89
Gallardo LP 560 – 4,Motor Diesel,2000,113045.0,False,"['Freios ABS', 'Teto panorâmico', 'Central mul...",144118.91
Chana Utility,Motor Diesel,2009,52034.0,False,"['Ar condicionado', 'Sensor de estacionamento'...",132662.32
TT Roadster,Motor Diesel,1998,107392.0,False,"['Ar condicionado', 'Sensor de estacionamento'...",85311.40
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Sandero,Motor Diesel,2015,34783.0,False,"['Piloto automático', 'Teto panorâmico', 'Câmb...",112350.61
XKR,Motor Diesel,1996,85127.0,False,"['Controle de tração', 'Ar condicionado', 'Tra...",54263.16
X5,Motor Diesel,2002,13606.0,False,"['Controle de tração', 'Piloto automático', 'T...",62041.32
Dodge Dakota,Motor Diesel,1993,71544.0,False,"['Controle de tração', 'Sensor de estacionamen...",141083.35
i30 CW,Motor Diesel,2015,8497.0,False,"['Sensor de chuva', 'Vidros elétricos', 'Contr...",73311.75
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79
V60,Motor Diesel,2004,91840.0,False,"['Rodas de liga', 'Sensor crepuscular', 'Ar co...",114728.74
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90

In [66]:
df[(select) & (df.Zero_km == True)]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79

In [67]:
df.query('Motor == "Motor Diesel" and Zero_km == True')

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79

##### <font color = antiquewhite> Iterations

In [69]:
list(df.iterrows())

[('Jetta Variant',
  Motor                                              Motor 4.0 Turbo
  Ano                                                           2003
  Quilometragem                                              44410.0
  Zero_km                                                      False
  Acessórios       ['Rodas de liga', 'Travas elétricas', 'Piloto ...
  Valor                                                     88078.64
  Name: Jetta Variant, dtype: object),
 ('Passat',
  Motor                                                 Motor Diesel
  Ano                                                           1991
  Quilometragem                                               5712.0
  Zero_km                                                      False
  Acessórios       ['Central multimídia', 'Teto panorâmico', 'Fre...
  Valor                                                    106161.94
  Name: Passat, dtype: object),
 ('Crossfox',
  Motor                                              Motor Diesel V8
  Ano                                                           1990
  Quilometragem                                              37123.0
  Zero_km                                                      False
  Acessórios       ['Piloto automático', 'Controle de estabilidad...
  Valor                                                     72832.16
  Name: Crossfox, dtype: object),
 ('DS5',
  Motor                                              Motor 2.4 Turbo
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Travas elétricas', '4 X 4', 'Vidros elétrico...
  Valor                                                    124549.07
  Name: DS5, dtype: object),
 ('Aston Martin DB4',
  Motor                                              Motor 2.4 Turbo
  Ano                                                           2006
  Quilometragem                                              25757.0
  Zero_km                                                      False
  Acessórios       ['Rodas de liga', '4 X 4', 'Central multimídia...
  Valor                                                      92612.1
  Name: Aston Martin DB4, dtype: object),
 ('Palio Weekend',
  Motor                                                Motor 1.8 16v
  Ano                                                           2012
  Quilometragem                                              10728.0
  Zero_km                                                      False
  Acessórios       ['Sensor de estacionamento', 'Teto panorâmico'...
  Valor                                                     97497.73
  Name: Palio Weekend, dtype: object),
 ('A5',
  Motor                                              Motor 4.0 Turbo
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Câmbio automático', 'Câmera de estacionament...
  Valor                                                      56445.2
  Name: A5, dtype: object),
 ('Série 3 Cabrio',
  Motor                                                 Motor 1.0 8v
  Ano                                                           2009
  Quilometragem                                              77599.0
  Zero_km                                                      False
  Acessórios       ['Controle de estabilidade', 'Sensor crepuscul...
  Valor                                                    112310.44
  Name: Série 3 Cabrio, dtype: object),
 ('Dodge Jorney',
  Motor                                                Motor 3.0 32v
  Ano                                                           2010
  Quilometragem                                              99197.0
  Zero_km                                                      False
  Acessórios       ['Vidros elétricos', 'Piloto automático', 'Tet...
  Valor                                                    120716.27
  Name: Dodge Jorney, dtype: object),
 ('Carens',
  Motor                                        Motor 5.0 V8 Bi-Turbo
  Ano                                                           2011
  Quilometragem                                              37978.0
  Zero_km                                                      False
  Acessórios       ['Ar condicionado', 'Painel digital', 'Central...
  Valor                                                     76566.49
  Name: Carens, dtype: object),
 ('Ford Edge',
  Motor                                              Motor Diesel V6
  Ano                                                           2002
  Quilometragem                                              12859.0
  Zero_km                                                      False
  Acessórios       ['Sensor crepuscular', 'Rodas de liga', 'Teto ...
  Valor                                                     71647.59
  Name: Ford Edge, dtype: object),
 ('Courier',
  Motor                                              Motor Diesel V8
  Ano                                                           2007
  Quilometragem                                               8052.0
  Zero_km                                                      False
  Acessórios       ['Central multimídia', '4 X 4', 'Piloto automá...
  Valor                                                     73919.53
  Name: Courier, dtype: object),
 ('S-18',
  Motor                                                     Motor V6
  Ano                                                           2001
  Quilometragem                                              89773.0
  Zero_km                                                      False
  Acessórios       ['Bancos de couro', 'Sensor de chuva', 'Rodas ...
  Valor                                                    112732.99
  Name: S-18, dtype: object),
 ('J5',
  Motor                                                     Motor V6
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Sensor crepuscular', 'Painel digital', 'Roda...
  Valor                                                     53183.38
  Name: J5, dtype: object),
 ('F-Type Coupé',
  Motor                                        Motor 5.0 V8 Bi-Turbo
  Ano                                                           2009
  Quilometragem                                              41457.0
  Zero_km                                                      False
  Acessórios       ['Piloto automático', 'Sensor crepuscular', 'S...
  Valor                                                    127488.42
  Name: F-Type Coupé, dtype: object),
 ('RAM',
  Motor                                              Motor Diesel V8
  Ano                                                           2016
  Quilometragem                                             115607.0
  Zero_km                                                      False
  Acessórios       ['Sensor crepuscular', 'Câmbio automático', 'S...
  Valor                                                      59910.4
  Name: RAM, dtype: object),
 ('Série 1',
  Motor                                                Motor 3.0 32v
  Ano                                                           2012
  Quilometragem                                              46449.0
  Zero_km                                                      False
  Acessórios       ['Teto panorâmico', 'Câmera de estacionamento'...
  Valor                                                     61118.59
  Name: Série 1, dtype: object),
 ('A3',
  Motor                                                 Motor 1.0 8v
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['4 X 4', 'Piloto automático', 'Central multim...
  Valor                                                     88552.39
  Name: A3, dtype: object),
 ('XC90',
  Motor                                                 Motor 1.0 8v
  Ano                                                           2016
  Quilometragem                                              37086.0
  Zero_km                                                      False
  Acessórios       ['Travas elétricas', 'Vidros elétricos', 'Teto...
  Valor                                                     62696.69
  Name: XC90, dtype: object),
 ('RS 3 Sportback',
  Motor                                                Motor 3.0 32v
  Ano                                                           2017
  Quilometragem                                              15173.0
  Zero_km                                                      False
  Acessórios       ['4 X 4', 'Piloto automático', 'Central multim...
  Valor                                                     101726.3
  Name: RS 3 Sportback, dtype: object),
 ('Pajero Sport',
  Motor                                                 Motor 1.0 8v
  Ano                                                           2002
  Quilometragem                                             101193.0
  Zero_km                                                      False
  Acessórios       ['Sensor de estacionamento', 'Piloto automátic...
  Valor                                                    106147.38
  Name: Pajero Sport, dtype: object),
 ('Série 1 M',
  Motor                                                     Motor V8
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Controle de estabilidade', 'Central multimíd...
  Valor                                                      94564.4
  Name: Série 1 M, dtype: object),
 ('Lamborghini Obvious',
  Motor                                              Motor Diesel V6
  Ano                                                           1994
  Quilometragem                                              98079.0
  Zero_km                                                      False
  Acessórios       ['Rodas de liga', 'Câmbio automático', 'Travas...
  Valor                                                    133529.84
  Name: Lamborghini Obvious, dtype: object),
 ('Effa Hafei Picape Baú',
  Motor                                                 Motor Diesel
  Ano                                                           1991
  Quilometragem                                             102959.0
  Zero_km                                                      False
  Acessórios       ['Controle de estabilidade', 'Painel digital',...
  Valor                                                    125684.65
  Name: Effa Hafei Picape Baú, dtype: object),
 ('Lamborghini Murciélago',
  Motor                                        Motor 5.0 V8 Bi-Turbo
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Freios ABS', 'Câmbio automático', 'Ar condic...
  Valor                                                    121596.21
  Name: Lamborghini Murciélago, dtype: object),
 ('Up!',
  Motor                                              Motor Diesel V6
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Sensor de estacionamento', 'Vidros elétricos...
  Valor                                                      71367.1
  Name: Up!, dtype: object),
 ('Fiesta Rocam Sedan',
  Motor                                              Motor 4.0 Turbo
  Ano                                                           2016
  Quilometragem                                               5795.0
  Zero_km                                                      False
  Acessórios       ['Ar condicionado', 'Bancos de couro', 'Câmbio...
  Valor                                                     95347.75
  Name: Fiesta Rocam Sedan, dtype: object),
 ('Sandero Stepway',
  Motor                                                Motor 3.0 32v
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Freios ABS', 'Ar condicionado', 'Teto panorâ...
  Valor                                                    105432.84
  Name: Sandero Stepway, dtype: object),
 ('Cayman S',
  Motor                                                Motor 3.0 32v
  Ano                                                           2002
  Quilometragem                                              58848.0
  Zero_km                                                      False
  Acessórios       ['Câmbio automático', 'Sensor de estacionament...
  Valor                                                     57045.27
  Name: Cayman S, dtype: object),
 ('V40',
  Motor                                              Motor 4.0 Turbo
  Ano                                                           1991
  Quilometragem                                              94381.0
  Zero_km                                                      False
  Acessórios       ['Câmera de estacionamento', 'Sensor de estaci...
  Valor                                                     120432.7
  Name: V40, dtype: object),
 ('Classe SLS AMG',
  Motor                                                 Motor 1.0 8v
  Ano                                                           1997
  Quilometragem                                              30163.0
  Zero_km                                                      False
  Acessórios       ['Sensor de estacionamento', 'Controle de esta...
  Valor                                                      70707.2
  Name: Classe SLS AMG, dtype: object),
 ('Gol G4',
  Motor                                                Motor 2.0 16v
  Ano                                                           1995
  Quilometragem                                              53332.0
  Zero_km                                                      False
  Acessórios       ['Sensor crepuscular', '4 X 4', 'Vidros elétri...
  Valor                                                     69105.18
  Name: Gol G4, dtype: object),
 ('Linea',
  Motor                                                 Motor 1.0 8v
  Ano                                                           2018
  Quilometragem                                              17720.0
  Zero_km                                                      False
  Acessórios       ['Piloto automático', 'Painel digital', 'Vidro...
  Valor                                                     59358.69
  Name: Linea, dtype: object),
 ('Ford F100',
  Motor                                                Motor 2.0 16v
  Ano                                                           1991
  Quilometragem                                              33808.0
  Zero_km                                                      False
  Acessórios       ['Controle de tração', 'Sensor crepuscular', '...
  Valor                                                      65955.4
  Name: Ford F100, dtype: object),
 ('J2',
  Motor                                                     Motor V8
  Ano                                                           2014
  Quilometragem                                              90684.0
  Zero_km                                                      False
  Acessórios       ['Teto panorâmico', 'Sensor de estacionamento'...
  Valor                                                     60017.03
  Name: J2, dtype: object),
 ('Aston Martin DBS',
  Motor                                                     Motor V8
  Ano                                                           1995
  Quilometragem                                              43975.0
  Zero_km                                                      False
  Acessórios       ['Teto panorâmico', 'Piloto automático', 'Ar c...
  Valor                                                    118909.52
  Name: Aston Martin DBS, dtype: object),
 ('Pajero TR4',
  Motor                                              Motor 2.4 Turbo
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Controle de tração', 'Bancos de couro', 'Câm...
  Valor                                                     51606.59
  Name: Pajero TR4, dtype: object),
 ('Polo Sedan',
  Motor                                                     Motor V6
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Sensor de chuva', 'Sensor crepuscular', 'Ar ...
  Valor                                                    123281.87
  Name: Polo Sedan, dtype: object),
 ('California',
  Motor                                                 Motor 1.0 8v
  Ano                                                           2009
  Quilometragem                                               5526.0
  Zero_km                                                      False
  Acessórios       ['Rodas de liga', 'Ar condicionado', 'Câmera d...
  Valor                                                     69770.18
  Name: California, dtype: object),
 ('S60',
  Motor                                              Motor 2.4 Turbo
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Teto panorâmico', 'Freios ABS', '4 X 4', 'Ar...
  Valor                                                    102609.54
  Name: S60, dtype: object),
 ('Tucson',
  Motor                                                Motor 2.0 16v
  Ano                                                           2013
  Quilometragem                                              93415.0
  Zero_km                                                      False
  Acessórios       ['Vidros elétricos', 'Sensor crepuscular', 'Fr...
  Valor                                                     67997.19
  Name: Tucson, dtype: object),
 ('HB20',
  Motor                                                     Motor V6
  Ano                                                           2003
  Quilometragem                                              40762.0
  Zero_km                                                      False
  Acessórios       ['Sensor de chuva', 'Travas elétricas', 'Contr...
  Valor                                                    135235.29
  Name: HB20, dtype: object),
 ('Optima',
  Motor                                                Motor 1.8 16v
  Ano                                                           2019
  Quilometragem                                                  NaN
  Zero_km                                                       True
  Acessórios       ['Central multimídia', 'Ar condicionado', 'Tet...
  Valor                                                     86641.34
  Name: Optima, dtype: object),
 ('Logan',

In [72]:
for index, row in df.iterrows():
    if(2019 - row['Ano'] != 0):
        df.loc[index, 'Km_media'] = row['Quilometragem'] / (2019 - row['Ano'])
    else:
        df.loc[index, 'Km_media'] = 0
df

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64,2775.625000
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94,204.000000
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16,1280.103448
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.000000
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10,1981.307692
...,...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58,5501.000000
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06,1070.750000
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03,3096.294118
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90,334.130435
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47,1858.814815

##### <font color = antiquewhite> Data treatment

In [73]:
# Replacing NaN values 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 258 entries, Jetta Variant to Macan
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Motor          258 non-null    object
 1   Ano            258 non-null    int64
 2   Quilometragem  197 non-null    float64
 3   Zero_km        258 non-null    bool
 4   Acessórios     258 non-null    object
 5   Valor          258 non-null    float64
 6   Km_media       258 non-null    float64
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 22.5+ KB

In [74]:
df.Quilometragem.isna()

Nome
Jetta Variant            False
Passat                   False
Crossfox                 False
DS5                       True
Aston Martin DB4         False
                         ...
Phantom 2013             False
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5         False
Macan                    False
Name: Quilometragem, Length: 258, dtype: bool

In [75]:
df[df.Quilometragem.isna()]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.0
A5,Motor 4.0 Turbo,2019,NaN,True,"['Câmbio automático', 'Câmera de estacionament...",56445.20,0.0
J5,Motor V6,2019,NaN,True,"['Sensor crepuscular', 'Painel digital', 'Roda...",53183.38,0.0
A3,Motor 1.0 8v,2019,NaN,True,"['4 X 4', 'Piloto automático', 'Central multim...",88552.39,0.0
Série 1 M,Motor V8,2019,NaN,True,"['Controle de estabilidade', 'Central multimíd...",94564.40,0.0
...,...,...,...,...,...,...,...
Lamborghini Reventón,Motor 4.0 Turbo,2019,NaN,True,"['Controle de tração', 'Ar condicionado', 'Cen...",67664.86,0.0
Benni Mini,Motor V8,2019,NaN,True,"['Sensor crepuscular', 'Câmbio automático', 'C...",126247.84,0.0
Uno,Motor Diesel V6,2019,NaN,True,"['Central multimídia', 'Sensor crepuscular', '...",128852.21,0.0
Santa Fe,Motor 3.0 32v,2019,NaN,True,"['Travas elétricas', 'Ar condicionado', '4 X 4...",129415.33,0.0
XC60,Motor 4.0 Turbo,2019,NaN,True,"['Painel digital', 'Piloto automático', 'Centr...",77675.79,0.0

In [81]:
df.Quilometragem.fillna(0, inplace=True)
df

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64,2775.625000
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94,204.000000
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16,1280.103448
DS5,Motor 2.4 Turbo,2019,0.0,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.000000
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10,1981.307692
...,...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58,5501.000000
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06,1070.750000
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03,3096.294118
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90,334.130435
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47,1858.814815

In [82]:
df.query('Zero_km == True')

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
DS5,Motor 2.4 Turbo,2019,0.0,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.0
A5,Motor 4.0 Turbo,2019,0.0,True,"['Câmbio automático', 'Câmera de estacionament...",56445.20,0.0
J5,Motor V6,2019,0.0,True,"['Sensor crepuscular', 'Painel digital', 'Roda...",53183.38,0.0
A3,Motor 1.0 8v,2019,0.0,True,"['4 X 4', 'Piloto automático', 'Central multim...",88552.39,0.0
Série 1 M,Motor V8,2019,0.0,True,"['Controle de estabilidade', 'Central multimíd...",94564.40,0.0
...,...,...,...,...,...,...,...
Lamborghini Reventón,Motor 4.0 Turbo,2019,0.0,True,"['Controle de tração', 'Ar condicionado', 'Cen...",67664.86,0.0
Benni Mini,Motor V8,2019,0.0,True,"['Sensor crepuscular', 'Câmbio automático', 'C...",126247.84,0.0
Uno,Motor Diesel V6,2019,0.0,True,"['Central multimídia', 'Sensor crepuscular', '...",128852.21,0.0
Santa Fe,Motor 3.0 32v,2019,0.0,True,"['Travas elétricas', 'Ar condicionado', '4 X 4...",129415.33,0.0
XC60,Motor 4.0 Turbo,2019,0.0,True,"['Painel digital', 'Piloto automático', 'Centr...",77675.79,0.0

In [83]:
df = pd.read_csv('db.csv',sep=';', index_col=0)

In [85]:
# Delete rows with NaN values
df.dropna(subset = ['Quilometragem'], inplace=True)
df

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
Palio Weekend,Motor 1.8 16v,2012,10728.0,False,"['Sensor de estacionamento', 'Teto panorâmico'...",97497.73
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47